      "\ 'g' : [':FloatermNew lazygit'                           , 'git'],
      "\ 'd' : [':FloatermNew lazydocker'                        , 'docker'],
      "\ 'n' : [':FloatermNew node'                              , 'node'],
      "\ 'N' : [':FloatermNew nnn'                               , 'nnn'],
      "\ 'p' : [':FloatermNew python'                            , 'python'],
     " \ 'r' : [':FloatermNew ranger'                            , 'ranger'],
      "\ 't' : [':FloatermToggle'                                , 'toggle'],
      "\ 'y' : [':FloatermNew ytop'                              , 'ytop'],
      "\ 's' : [':FloatermNew ncdu'                              , 'ncdu'],
